---
title: "Class 18 - Lecture"
author: Hari Subhash
date: "Date created: `r Sys.Date()`"
output:
  html_notebook: 
    df_print: paged
    highlight: haddock
    theme: readable
---
## **Learning objectives**
1. Write our first function
2. Map a function to elements of a vector


```{r}
sum_nums <- function(x, y) {
  x + y
}
```

Lets call our function

```{r}
sum_nums(45, 90)
```


Lets look at the different ways to return a value from a function

```{r}
sum_nums_explicit <- function(x, y) {
  return(x + y)
}

sum_nums_explicit(45, 90)
```


```{r}
sum_nums_stored <- function(x, y) {
  stored_val <- x + y
}

out_stored <- sum_nums_stored(45, 90)

out_stored
```

Check on this last evaluated business

```{r}
sum_nums_stored <- function(x, y) {
  test_1 <- 1 + 34
  
  x
  
  stored_val <- x + y
}

out_stored <- sum_nums_stored(45, 90)

out_stored
```

The reason to use an explicit return

```{r}
sum_nums_stored <- function(x, y) {
  test_1 <- 1 + 34
  
  return(x)
  
  stored_val <- x + y
}

out_stored <- sum_nums_stored(45, 90)

out_stored
```

##Lets look at mapping
```{r}
glimpse(gapminder)
```


Lets try for loop
```{r}
## a modified draw_hist
draw_hist <- function(num_vec) {
    if (is.numeric(num_vec)) hist(num_vec) else NULL
}
```


```{r}
for (i in seq_along(gapminder)) {
  draw_hist(gapminder[[i]])
}
```


Now lets do the same thing with map
```{r}
map(gapminder, draw_hist)
```








