---
title: "Class 8 - In class exercises"
author: Hari Subhash
date: "Date created: `r Sys.Date()`"
output:
  html_notebook:
    highlight: kate
    smart: yes
    theme: cosmo
    code_folding: show
    df_print: paged
---

##Task Set 1: Correct me

```{r}
library(nycflights13); library(tidyverse)

meanCarrierDelays <- flights %>% 
    group_by(carrier) %>% 
    summarise(meanDelay = mean(dep_delay, na.rm = T))
```


```{r}
flights %>% 
    group_by(origin) %>% 
    summarise(medianDelay = median(dep_delay, na.rm = T), 
              stdDevDelay = sd(dep_delay, na.rm = T))
```


```{r}
##this code fails silently. Correct it so that the newDate column shows the actual date
flights %>% 
    mutate(newDate = paste(year, month, day, sep = "-")) %>% 
    select(1:3, "newDate")
```

```{r}
##This code fails silently. I would like a column chart that shows the average positive departure delay for each carrier, this chart is showing me something else entirely.
flights %>% 
    filter(dep_delay > 0) %>% 
    group_by(orgin) %>% 
    ggplot(aes(x = carrier, y = mean(dep_delay, na.rm = T))) +
    geom_col()
```

```{r}
flights %>% 
    filter(dep_delay > 0) %>% 
    summarise(meanDelay = mean(dep_delay, na.rm = T))
```


```{r}
flights %>% 
    filter(dep_delay > 0) %>%
    group_by(carrier) %>% 
    summarise(nObsTimesMean = n() * 39.37323) %>% 
    ggplot(aes(x = carrier, y = nObsTimesMean)) +
    geom_col()
```

This is the correct answer.
```{r}
flights %>% 
    filter(dep_delay > 0) %>% 
    group_by(carrier) %>% 
    summarise(meanDelay = mean(dep_delay, na.rm = T)) %>% 
    ungroup() %>% 
    ggplot(mapping = aes(x = carrier, y = meanDelay)) +
    geom_col()
```

**Hard Task**: Can you explain the chart that was being plotted in the above chunk before you corrected it?





