---
title: "Class 6 - In class exercises"
author: Hari Subhash
date: "Date created: `r Sys.Date()`"
output:
  html_notebook:
    highlight: kate
    smart: yes
    theme: cosmo
    code_folding: show
    df_print: paged
---

##Task Set 1: Practice Practice Practice
**Time**: 30 minutes

1. Install the 'gapminder' package. If you are using the `install.packages()` function to do this, make sure to delete the function once the package is installed.
2. Why should you delete the `install.packages()` function from your notebook once you run it?
3. Use `?gapminder` to access the help file for the dataset called `gapminder` from the gapminder package. Copy and paste the description of the dataset below.
4. Use `head()` to print the first 10 rows of the gapminder dataset.
5. Use `tail()` to print the last 20 rows of the gapminder dataset.
6. Use `str()` to see the structure of the gapminder dataset.
7. Use `glimpse()` to see the structure of the gapminder dataset.
8. Use `names()` to print the names of the columns in the gapminder dataset
9. Draw a histogram of the `gdpPerCap` variable in the gapminder dataset. 
10. Draw a histogram of the `gdpPerCap` but this time add a binwidth argument to the histogram. Use a value of your choice.
11. Filter the gapminder dataset to show only the latest year for each country. (Hint: you will need to group the data and filter for the most recent year using year == `max(year, na.rm = T)`, figure out the variable you should group by.)
12. Do the same steps as in 11 but this time pipe to a ggplot function that plots a histogram.
13. Observe the differences in the histogram from 12 and 10.
14. Find the average population every year and show that on a column chart
15. Find the average population every year and show that on a line chart
16. Draw a scatter plot showing the relationship between population and gddPercap for latest year for every country (same process as 11)
17. The previous scatter looks weird. You can improve this by plotting the log(pop) against the log(gdpPercap). Try doing this. A Log transformation is useful to highlight underlying patterns in highly skewed data (long tails). 
18. Draw a boxplot showing the spread of gdpPercap for each year since 2000 (so x is year and y is gdpPercap). Make sure to wrap your year variable in `factor()` or a `as.character()` so that it is not treated as a continous variable.
19. Add a `facet_wrap()` with continents as the facets.
20. Modify the `facet_wrap()` function so that all the charts display in a single row. Look at the help file for `facet_wrap()` to figure out how to do this.

##Task Set 2: Make me pretty
**Time**: 10 minutes

1. Pick any of the charts that you made in the previous section and make it pretty
    + Add axis labels and chart title
    + Any additional aesthetics to make it prettier
    + Choose a theme template (either from ggthemes or from ggplot) (Beware: some of the themes have effects on things like axis titles, text etc.)
    + Make any additional changes you would like to make it more attractive
2. Save this plot using `ggsave()` as a png and share it on the class4 channel.


##Task Set 3: Extra time
**Time**: 30 minutes

1. Create a multiline chart showing the gdpPercap trends over the years for different continents.  Each continent should have a line that is a different colour from the others. Make it pretty.

```{r}
gapminder %>% 
    group_by(continent, year) %>% 
    summarise(meanGDP = mean(gdpPercap, na.rm = T)) %>% 
    ggplot(aes(x = year, y = meanGDP, colour = continent)) +
    geom_line() +
    directlabels::geom_dl(aes(label = continent), method = "last.bumpup")
```

2. Install the directlabels package.
3. Use the `geom_dl()` function from this package to attach labels showing the names of the continents right next to the line. Make sure the labels have the same colour as the lines and that they are visible. Remove the legend using the `theme()` function. Check out different positioning methods here: http://directlabels.r-forge.r-project.org/docs/index.html
4. Install the cowplots package.
5. Create the same plot as above but this time save it to a variable. Create the exact same plot but for population instead of gdpPercap. Use `plot_grid()` from the cowplots package to show these two plots next to each other. 


