---
title: "Class 2 - Lecture"
author: Hari Subhash
date: "Date created: `r Sys.Date()`"
output:
  html_notebook:
    highlight: kate
    smart: yes
    theme: cosmo
    code_folding: show
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float: true
css: /Users/hsubhash/Documents/R4D/Assets/custom.css
---
##Packages Used
1. tidyverse. Specifically dplyr from within the tidyverse
2. nycflights13 a dataset containing all the flights that took off from NYC in 2013.
3. lubridate a tidyverse package to handle dates in R

##Learning Objectives
1. Use slack to ask questions more effectively
2. Understand material from class 1
3. Install and load packages
4. Use the tidyverse portal to access information
5. Explain the use of pipes and the dot symbol
6. Arrange/sort a table
7. Select columns from tabular data
8. Filter rows from tabular data
9. Mutate tabular data
10. Host your notebook online using github


##Review material from class 1
1. Variable assignment
2. Data types: Create three different data types
3. Data structures: Create a vector, a list and a data.frame

##Arrange a table
1. Introduction to the nycflights13 package
2. Introduction to tibbles
3. Arrange the flights data using the departure delay variable
4. Arrange the flights data using two different variables

##Select columns from a tibble
1. Using columns numbers
2. Remove using negative indices
3. Select by name
4. Using name range

##Filter
1. Introduce all the relational and logical operators in R
2. Filter by a numeric value
3. Filter by a character value
5. Use logical operators to combine filter conditions

##Mutate
1. Use the lubridate package to create a new date variable and arrange it in descending order
2. Use `if_else()` syntax to create a variable that indicates whether a flight was delayed.


```{r}
source("../helpers.R")

pickRandom()
```

